import type { ui as en } from '../en/ui';

/** Интерфейс, общий для всех масштабов (HUD, инспектор, режимы просмотра, тур). */
export const ui: typeof en = {
  traceSignal: 'Проследить сигнал ▸',
  followIntoDie: 'За ним в кристалл ▸',
  diveIntoSm: 'Нырнуть в SM ▸',
  endTrace: 'Закончить трассировку',
  recentre: 'По центру',
  dive: (scale: string) => `Нырнуть ▸ ${scale}`,
  back: (scale: string) => `◂ ${scale}`,
  explore: (scale: string) => `Исследование · ${scale}`,
  exploreHintPick:
    'Наведите на деталь, чтобы узнать, что это, нажмите, чтобы рассмотреть. Тяните, чтобы вращать, колесо — масштаб.',
  exploreHintPlain: 'Тяните, чтобы вращать, колесо — масштаб.',
  traceStage: (i: number, n: number, kind: string) => `Трасса ${i}/${n} · ${kind}`,
  follow: 'Трасса',
  static: {
    docTitle: 'От GPU до атома',
    docDescription: '3D-разбор видеокарты на прокрутке: от кожуха до одного атома кремния и кварков в его ядре.',
    brand: 'АТОМ',
    language: 'Язык',
    crumbs: 'Путь по масштабам',
    explore: 'Исследовать',
    exploreTitle: 'Режим исследования (E)',
    prevTitle: 'Предыдущий масштаб (←)',
    nextTitle: 'Следующий масштаб (→)',
    followTitle: 'Проследить один бит от слота PCIe до одного атома (F)',
    labels: 'Подписи',
    labelsTitle: '3D-подписи (L)',
    soundTitle: 'Фоновый звук (M)',
    scrollHint: 'прокрутите вниз',
    fovLabel: 'поле зрения',
    tipHint: 'нажмите, чтобы рассмотреть',
    exploreHintMouse: 'тянуть · вращать   колесо · масштаб   правая кнопка · сдвиг   клик · деталь   esc · выход',
    exploreHintTouch: '1 палец · вращать   щипок · масштаб   2 пальца · сдвиг   касание · деталь',
    collapse: 'Свернуть',
    closeEsc: 'Закрыть (Esc)',
    endTour: 'Закончить тур',
    soundInvite: 'У этого спуска есть звук. Фоновый, процедурный, по умолчанию выключен.',
    soundOn: 'Включить',
    soundNo: 'Не надо',
    finTag: 'Конец спуска',
    finTitle: 'Вы на самом дне.',
    finSub: 'Четырнадцать порядков величины. Один объект — до самого конца.',
    finGpu: 'GPU',
    finTransistor: 'Транзистор',
    finSilicon: 'Кремний',
    finAtom: 'Атом',
    finQuarks: 'Кварки',
    fin30cm: '30 см',
    fin50nm: '50 нм',
    fin2nm: '2 нм',
    fin02nm: '0,2 нм',
    fin1fm: '1 фм',
    finTransistorsValue: '92,2 млрд',
    finTransistors: 'транзисторов',
    finMetal: 'слоёв металла',
    finAtomValue: '≈0,1 нм',
    finAtomWidth: 'поперёк атома',
    replay: 'Ещё раз',
    shareFrame: 'Сохранить кадр',
    shareLink: 'Поделиться',
    shareLinkCopied: 'Ссылка скопирована',
    starGithub: '\u2605 Звезда на GitHub',
    sourcesGlossary: 'Источники и глоссарий',
    sourceCredits: 'Код и авторы',
    memoryBranch: 'Боковая ветка: память ▸',
    introTitle1: 'Один спуск.',
    introTitle2: 'Четырнадцать порядков величины.',
    introLede:
      'От 30-сантиметровой видеокарты до атома кремния в её сердце и дальше, до кварков в его ядре — смоделировано и отрисовано прямо в браузере. Без видео и скачанных моделей.',
    introStart: 'Начать спуск',
    introScroll: 'Листать самому',
    introKeys: 'пробел пуск / пауза  ·  e исследовать  ·  shift+f полный экран',
  },
  number: {
    decimal: ',',
    units: { m: 'м', cm: 'см', mm: 'мм', µm: 'мкм', nm: 'нм', Å: 'Å', pm: 'пм', fm: 'фм' },
  },
  options: {
    // Режимы просмотра
    Normal: 'Обычный',
    'X-Ray': 'Рентген',
    Section: 'Разрез',
    Thermal: 'Нагрев',
    // Вентиляторы
    Stop: 'Стоп',
    Idle: 'Простой',
    Load: 'Нагрузка',
    // Поток данных
    Off: 'Выкл',
    Slow: 'Медленно',
    Realtime: 'Обычно',
    Burst: 'Пакетами',
    // Подсветка кристалла
    None: 'Нет',
    Memory: 'Память',
    // Затвор
    OFF: 'ВЫКЛ',
    ON: 'ВКЛ',
    CLOCK: 'ТАКТ',
    MANUAL: 'ВРУЧНУЮ',
    // Легирование
    Mixed: 'Смешанное',
    Intrinsic: 'Чистый',
    'N-type': 'n-тип',
    'P-type': 'p-тип',
    // Орбитали
    All: 'Все',
    // Слои протона
    Valence: 'Валентные',
    Gluons: 'Глюоны',
    Sea: 'Морские',
  },
  stop: 'Стоп',
  sound: { on: 'Звук вкл', off: 'Звук' },
  ruler: {
    label: 'Линейка масштаба, логарифмическая',
    marks: [
      { m: 1.7, text: 'человек' },
      { m: 1e-2, text: 'ноготь' },
      { m: 7e-5, text: 'волос' },
      { m: 7e-6, text: 'эритроцит' },
      { m: 1e-7, text: 'вирус' },
      { m: 2e-9, text: 'ДНК' },
      { m: 2e-10, text: 'атом' },
      { m: 6e-15, text: 'ядро' },
    ],
  },
  palette: {
    scale: (n: number) => `Масштаб ${String(n).padStart(2, '0')}`,
    part: 'Деталь',
    view: 'Вид',
    labels: 'Показать 3D-подписи',
    fullscreen: 'Полный экран',
    glossary: 'Глоссарий',
    sources: 'Источники',
  },
  scaleAnchors: [
    [0.2, 'пядь'],
    [0.04, 'рисовое зерно'],
    [0.007, 'ноготь'],
    [9e-4, 'песчинка'],
    [5e-5, 'человеческий волос'],
    [6e-6, 'эритроцит'],
    [6e-7, 'бактерия'],
    [4e-7, 'длина волны света'],
    [4e-8, 'вирус'],
    [5e-9, 'нить ДНК'],
    [3.5e-10, 'несколько атомов кремния'],
    [5e-11, 'один атом'],
    [4e-15, 'атомное ядро'],
  ],
  scaleAnchorSmallest: 'один протон',
  views: {
    view: 'Вид',
    cut: 'Положение разреза',
  },
  thermal: {
    load: 'Нагрузка GPU',
    fans: 'Вентиляторы',
    boardPower: 'Мощность платы',
    hotspot: 'Горячая точка (оценка)',
    clocks: 'Частоты',
    throttling: (pct: number) => `ТРОТТЛИНГ ${pct}%`,
    fullBoost: 'полный буст',
    model: 'Модель',
    flow: (from: string, to: string) => `${from} → ${to}`,
    toAir: 'В воздух',
    illustrative: 'иллюстрация, не замер',
  },
};
