/** Interface text shared by every level (HUD, inspector, view modes, tour). */
export const ui = {
  traceSignal: 'Trace signal ▸',
  followIntoDie: 'Follow into the die ▸',
  diveIntoSm: 'Dive into the SM ▸',
  endTrace: 'End trace',
  recentre: 'Re-centre',
  dive: (scale: string) => `Dive ▸ ${scale}`,
  back: (scale: string) => `◂ ${scale}`,
  explore: (scale: string) => `Explore · ${scale}`,
  exploreHintPick: 'Hover anything to identify it, click to inspect. Drag to orbit, wheel to zoom.',
  exploreHintPlain: 'Drag to orbit, wheel to zoom.',
  traceStage: (i: number, n: number, kind: string) => `Trace ${i}/${n} · ${kind}`,
  follow: 'Trace',
  /** Text that ships in index.html, re-applied from here so every language comes from one place. */
  static: {
    // Keys match the data-i18n / data-i18n-title / data-i18n-aria attributes in index.html.
    docTitle: 'GPU to Atom',
    docDescription:
      'Scroll-driven 3D teardown of a graphics card, from the shroud down to a single silicon atom and the quarks in its nucleus.',
    brand: 'ATOM',
    language: 'Language',
    crumbs: 'Scale breadcrumb',
    explore: 'Explore',
    exploreTitle: 'Explore mode (E)',
    prevTitle: 'Previous scale (←)',
    nextTitle: 'Next scale (→)',
    followTitle: 'Trace one bit from the PCIe slot down to a single atom (F)',
    labels: 'Labels',
    labelsTitle: '3D labels (L)',
    soundTitle: 'Ambient sound (M)',
    scrollHint: 'scroll to descend',
    fovLabel: 'field of view',
    tipHint: 'click to inspect',
    exploreHintMouse: 'drag · orbit   wheel · zoom   right-drag · pan   click · inspect   esc · exit',
    exploreHintTouch: '1 finger · orbit   pinch · zoom   2 fingers · pan   tap · inspect',
    collapse: 'Collapse',
    closeEsc: 'Close (Esc)',
    endTour: 'End tour',
    soundInvite: 'This descent has a sound. Ambient, procedural, off by default.',
    soundOn: 'Turn it on',
    soundNo: 'No thanks',
    finTag: 'End of the descent',
    finTitle: 'You reached the bottom.',
    finSub: 'Fourteen orders of magnitude. One object, all the way down.',
    finGpu: 'GPU',
    finTransistor: 'Transistor',
    finSilicon: 'Silicon',
    finAtom: 'Atom',
    finQuarks: 'Quarks',
    fin30cm: '30 cm',
    fin50nm: '50 nm',
    fin2nm: '2 nm',
    fin02nm: '0.2 nm',
    fin1fm: '1 fm',
    finTransistorsValue: '92.2 B',
    finTransistors: 'transistors',
    finMetal: 'metal layers',
    finAtomValue: '≈0.1 nm',
    finAtomWidth: 'across an atom',
    replay: 'Replay',
    shareFrame: 'Share frame',
    shareLink: 'Share link',
    shareLinkCopied: 'Link copied',
    starGithub: '\u2605 Star on GitHub',
    sourcesGlossary: 'Sources & glossary',
    sourceCredits: 'Source & credits',
    memoryBranch: 'Side branch: memory ▸',
    introTitle1: 'One descent.',
    introTitle2: 'Fourteen orders of magnitude.',
    introLede:
      'From a 30 cm graphics card to the silicon atom at its heart, and on into the quarks of its nucleus — modelled and rendered live in your browser. No video, no downloaded assets.',
    introStart: 'Start the descent',
    introScroll: 'Scroll it yourself',
    introKeys: 'space play / pause \u00a0·\u00a0 e explore \u00a0·\u00a0 shift+f fullscreen',
  },
  /** Length units and the decimal mark for live readouts (scale bar, field of view). */
  number: {
    decimal: '.',
    units: { m: 'm', cm: 'cm', mm: 'mm', µm: 'µm', nm: 'nm', Å: 'Å', pm: 'pm', fm: 'fm' },
  },
  /** Choice-control options are stable ids in code; this maps the ones that need a translation. */
  options: {} as Record<string, string>,
  stop: 'Stop',
  sound: { on: 'Sound on', off: 'Sound' },
  /** The logarithmic ruler: familiar objects at their real size (metres). */
  ruler: {
    label: 'Scale ruler, logarithmic',
    marks: [
      { m: 1.7, text: 'a person' },
      { m: 1e-2, text: 'a fingernail' },
      { m: 7e-5, text: 'a hair' },
      { m: 7e-6, text: 'a blood cell' },
      { m: 1e-7, text: 'a virus' },
      { m: 2e-9, text: 'DNA' },
      { m: 2e-10, text: 'an atom' },
      { m: 6e-15, text: 'a nucleus' },
    ] as { m: number; text: string }[],
  },
  palette: {
    scale: (n: number) => `Scale ${String(n).padStart(2, '0')}`,
    part: 'Part',
    view: 'View',
    labels: 'Toggle 3D labels',
    fullscreen: 'Fullscreen',
    glossary: 'Glossary',
    sources: 'Sources',
  },
  /** Scale bar: a familiar object at least `min` metres long. */
  scaleAnchors: [
    [0.2, 'a hand span'],
    [0.04, 'a grain of rice'],
    [0.007, 'a fingernail'],
    [9e-4, 'a grain of sand'],
    [5e-5, 'a human hair'],
    [6e-6, 'a red blood cell'],
    [6e-7, 'a bacterium'],
    [4e-7, 'a wavelength of light'],
    [4e-8, 'a virus'],
    [5e-9, 'a strand of DNA'],
    [3.5e-10, 'a few silicon atoms'],
    [5e-11, 'a single atom'],
    [4e-15, 'an atomic nucleus'],
  ] as [number, string][],
  scaleAnchorSmallest: 'a single proton',
  views: {
    view: 'View',
    cut: 'Cut position',
  },
  thermal: {
    load: 'GPU load',
    fans: 'Fans',
    boardPower: 'Board power',
    hotspot: 'Hotspot (est.)',
    clocks: 'Clocks',
    throttling: (pct: number) => `THROTTLING ${pct}%`,
    fullBoost: 'full boost',
    model: 'Model',
    flow: (from: string, to: string) => `${from} → ${to}`,
    toAir: 'Into the air',
    illustrative: 'illustrative, not measured',
  },
};
