/** Interface text shared by every level (HUD, inspector, view modes, tour). */
export const ui = {
  traceSignal: 'Trace signal ▸',
  followIntoDie: 'Follow into the die ▸',
  diveIntoSm: 'Dive into the SM ▸',
  endTrace: 'End trace',
  recentre: 'Re-centre',
  dive: (scale: string) => `Dive ▸ ${scale}`,
  back: (scale: string) => `◂ ${scale}`,
  explore: (scale: string) => `Explore · ${scale}`,
  exploreHintPick: 'Hover anything to identify it, click to inspect. Drag to orbit, wheel to zoom.',
  exploreHintPlain: 'Drag to orbit, wheel to zoom.',
  traceStage: (i: number, n: number, kind: string) => `Trace ${i}/${n} · ${kind}`,
  follow: 'Trace',
  /** Text that ships in index.html, re-applied from here so every language comes from one place. */
  static: {
    explore: 'Explore',
    scrollHint: 'scroll to descend',
    fovLabel: 'field of view',
    tipHint: 'click to inspect',
    exploreHintMouse: 'drag · orbit   wheel · zoom   right-drag · pan   click · inspect   esc · exit',
    exploreHintTouch: '1 finger · orbit   pinch · zoom   2 fingers · pan   tap · inspect',
  },
  stop: 'Stop',
  sound: { on: 'Sound on', off: 'Sound' },
  /** The logarithmic ruler: familiar objects at their real size (metres). */
  ruler: {
    label: 'Scale ruler, logarithmic',
    marks: [
      { m: 1.7, text: 'a person' },
      { m: 1e-2, text: 'a fingernail' },
      { m: 7e-5, text: 'a hair' },
      { m: 7e-6, text: 'a blood cell' },
      { m: 1e-7, text: 'a virus' },
      { m: 2e-9, text: 'DNA' },
      { m: 2e-10, text: 'an atom' },
    ] as { m: number; text: string }[],
  },
  palette: {
    scale: (n: number) => `Scale ${String(n).padStart(2, '0')}`,
    part: 'Part',
    view: 'View',
    labels: 'Toggle 3D labels',
    fullscreen: 'Fullscreen',
    glossary: 'Glossary',
    sources: 'Sources',
  },
  /** Scale bar: a familiar object at least `min` metres long. */
  scaleAnchors: [
    [0.2, 'a hand span'],
    [0.04, 'a grain of rice'],
    [0.007, 'a fingernail'],
    [9e-4, 'a grain of sand'],
    [5e-5, 'a human hair'],
    [6e-6, 'a red blood cell'],
    [6e-7, 'a bacterium'],
    [4e-7, 'a wavelength of light'],
    [4e-8, 'a virus'],
    [5e-9, 'a strand of DNA'],
    [3.5e-10, 'a few silicon atoms'],
  ] as [number, string][],
  scaleAnchorSmallest: 'a single atom',
  views: {
    view: 'View',
    cut: 'Cut position',
  },
  thermal: {
    load: 'GPU load',
    fans: 'Fans',
    boardPower: 'Board power',
    hotspot: 'Hotspot (est.)',
    clocks: 'Clocks',
    throttling: (pct: number) => `THROTTLING ${pct}%`,
    fullBoost: 'full boost',
    model: 'Model',
    flow: (from: string, to: string) => `${from} → ${to}`,
    toAir: 'Into the air',
    illustrative: 'illustrative, not measured',
  },
};
