import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import type { Plugin, ResolvedConfig } from 'vite';

/**
 * Writes dist/sw.js after the build: a service worker that precaches every file of the build
 * (the app is fully procedural, so that is the whole experience, ~1.5 MB) and serves it offline.
 * The cache name is a hash of the build, so each deploy replaces the previous cache.
 */
export function serviceWorker(): Plugin {
  let config: ResolvedConfig;
  return {
    name: 'gpu-atom-sw',
    apply: 'build',
    configResolved(c) {
      config = c;
    },
    writeBundle() {
      const outDir = config.build.outDir;
      const files = walk(outDir)
        .map((f) => relative(outDir, f).split(sep).join('/'))
        .filter((f) => f !== 'sw.js')
        .sort();
      const hash = createHash('sha256');
      for (const f of files) hash.update(f).update(readFileSync(join(outDir, f)));
      const version = hash.digest('hex').slice(0, 12);
      writeFileSync(join(outDir, 'sw.js'), source(version, files));
    },
  };
}

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const source = (version: string, files: string[]) => `// Generated by scripts/pwa-plugin.ts. Do not edit.
const CACHE = 'gpu-atom-${version}';
const PRECACHE = ${JSON.stringify(['./', ...files.map((f) => `./${f}`)])};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('gpu-atom-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;

  // Pages: network first so a new deploy shows up, the cached shell when offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put('./', copy));
          }
          return response;
        })
        .catch(() => caches.match('./', { cacheName: CACHE })),
    );
    return;
  }

  // Everything else is content-hashed or versioned with the cache: cache first.
  event.respondWith(
    caches.match(request, { cacheName: CACHE }).then(
      (hit) =>
        hit ||
        fetch(request).then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        }),
    ),
  );
});
`;
